package shares.brokering.client;

import org.me.sharesbrokeringsystem.Company;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bartek
 */
public class ShareInfo extends javax.swing.JFrame 
{
    Company company;
    /**
     * Creates new form ShareInfo
     * @param _company
     */
    public ShareInfo(Company _company) 
    {
        initComponents();
        company = _company;
        nameLabel.setText(company.getName());
        symbolLabel.setText(company.getSymbol());
        sectorLabel.setText(company.getSector());
        volumeLabel.setText(company.getVolume());
        
        currentValueLabel.setText(Double.toString(Math.floor(company.getPrice().getValue() * 100) / 100));
        openValueLabel.setText(Double.toString(Math.floor(company.getPrice().getOpenValue() * 100) / 100));
        closeValueLabel.setText(Double.toString(Math.floor(company.getPrice().getCloseValue() * 100) / 100));
        highValueLabel.setText(Double.toString(Math.floor(company.getPrice().getHighValue() * 100) / 100));
        lowValueLabel.setText(Double.toString(Math.floor(company.getPrice().getLowValue() * 100) / 100));
        CurrencyLabel.setText(company.getPrice().getCurrency());
        String dateString = company.getPrice().getLastUpdate().toString();
        dateString = dateString.replace("T", " ");
        dateString = dateString.replace("Z", "");
        dateString = dateString.substring(0, dateString.length() - 4);
        lastUpdateLabel.setText(dateString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        nameTextLabel = new javax.swing.JLabel();
        SymbolTextLabel = new javax.swing.JLabel();
        SectorTextLabel = new javax.swing.JLabel();
        VolumeTextLabel = new javax.swing.JLabel();
        currentValueTextLabel = new javax.swing.JLabel();
        openValueTextLabel = new javax.swing.JLabel();
        closeValueTextLabel = new javax.swing.JLabel();
        highValueTextLabel = new javax.swing.JLabel();
        lowValueTextLabel = new javax.swing.JLabel();
        symbolLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        sectorLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        currentValueLabel = new javax.swing.JLabel();
        openValueLabel = new javax.swing.JLabel();
        closeValueLabel = new javax.swing.JLabel();
        highValueLabel = new javax.swing.JLabel();
        lowValueLabel = new javax.swing.JLabel();
        lastUpdateTextLabel = new javax.swing.JLabel();
        lastUpdateLabel = new javax.swing.JLabel();
        CurrencyTextLabel = new javax.swing.JLabel();
        CurrencyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        nameTextLabel.setText("Name:");

        SymbolTextLabel.setText("Symbol:");

        SectorTextLabel.setText("Sector:");

        VolumeTextLabel.setText("Volume:");

        currentValueTextLabel.setText("Current Value:");

        openValueTextLabel.setText("Open Value:");

        closeValueTextLabel.setText("Close Value:");

        highValueTextLabel.setText("High Value:");

        lowValueTextLabel.setText("Low Value:");

        lastUpdateTextLabel.setText("Last Update:");

        CurrencyTextLabel.setText("Currency:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VolumeTextLabel)
                    .addComponent(SectorTextLabel)
                    .addComponent(SymbolTextLabel)
                    .addComponent(nameTextLabel)
                    .addComponent(lastUpdateTextLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastUpdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(symbolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sectorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CurrencyTextLabel)
                            .addComponent(lowValueTextLabel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(highValueTextLabel))
                        .addComponent(currentValueTextLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(closeValueTextLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(openValueTextLabel, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(highValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lowValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentValueTextLabel)
                            .addComponent(currentValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openValueTextLabel)
                            .addComponent(openValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeValueTextLabel)
                            .addComponent(closeValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(highValueTextLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(highValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lowValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lowValueTextLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CurrencyTextLabel)
                            .addComponent(CurrencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SymbolTextLabel)
                            .addComponent(symbolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sectorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(volumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SectorTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VolumeTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastUpdateTextLabel)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrencyLabel;
    private javax.swing.JLabel CurrencyTextLabel;
    private javax.swing.JLabel SectorTextLabel;
    private javax.swing.JLabel SymbolTextLabel;
    private javax.swing.JLabel VolumeTextLabel;
    private javax.swing.JLabel closeValueLabel;
    private javax.swing.JLabel closeValueTextLabel;
    private javax.swing.JLabel currentValueLabel;
    private javax.swing.JLabel currentValueTextLabel;
    private javax.swing.JLabel highValueLabel;
    private javax.swing.JLabel highValueTextLabel;
    private javax.swing.JLabel lastUpdateLabel;
    private javax.swing.JLabel lastUpdateTextLabel;
    private javax.swing.JLabel lowValueLabel;
    private javax.swing.JLabel lowValueTextLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameTextLabel;
    private javax.swing.JLabel openValueLabel;
    private javax.swing.JLabel openValueTextLabel;
    private javax.swing.JLabel sectorLabel;
    private javax.swing.JLabel symbolLabel;
    private javax.swing.JLabel volumeLabel;
    // End of variables declaration//GEN-END:variables
}
